=== jeniq/Project3/src/com/company/xml/Weapon.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="gun">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="weapon" maxOccurs="unbounded" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element type="xs:string" name="model"/>
                            <xs:element name="handy">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:enumeration value="ONE_HANDED" />
                                        <xs:enumeration value="TWO_HANDED" />
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element type="xs:string" name="origin"/>
                            <xs:element name="ttc">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="range">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                    <xs:pattern value="short-[1-4][0-9]{2}" />
                                                    <xs:pattern value="middle-[5-9][0-9]{2}" />
                                                    <xs:pattern value="high-[0-4][0-9]{3}" />
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="effectiveRange">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:int">
                                                    <xs:minInclusive value="5" />
                                                    <xs:maxInclusive value="4999" />
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element type="xs:boolean" name="holder"/>
                                        <xs:element type="xs:boolean" name="optics"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element type="xs:string" name="material"/>
                        </xs:sequence>
                        <xs:attribute type="xs:string" name="id" use="required"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== jeniq/Project3/out/production/Project3/com/company/xml/Weapon.xml
<?xml version="1.0" encoding="UTF-8"?>

<gun xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="Weapon.xsd">
    <weapon id = "gun1">
        <model>M16A4</model>
        <handy>TWO_HANDED</handy>
        <origin>USA</origin>
        <ttc>
            <range>middle-800</range>
            <effectiveRange>600</effectiveRange>
            <holder>true</holder>
            <optics>true</optics>
        </ttc>
        <material>steel, aluminum, plastic</material>
    </weapon>

    <weapon id = "gun2">
        <model>Desert Eagle</model>
        <handy>ONE_HANDED</handy>
        <origin>Israel</origin>
        <ttc>
            <range>short-200</range>
            <effectiveRange>120</effectiveRange>
            <holder>true</holder>
            <optics>false</optics>
        </ttc>
        <material>steel, aluminum,</material>
    </weapon>

    <weapon id = "gun3">
        <model>AK-47</model>
        <handy>TWO_HANDED</handy>
        <origin>Russia</origin>
        <ttc>
            <range>high-3000</range>
            <effectiveRange>1500</effectiveRange>
            <holder>true</holder>
            <optics>false</optics>
        </ttc>
        <material>steel, plastic</material>
    </weapon>

    <weapon id = "gun4">
        <model>Negev NG7</model>
        <handy>TWO_HANDED</handy>
        <origin>Israel</origin>
        <ttc>
            <range>high-4000</range>
            <effectiveRange>2000</effectiveRange>
            <holder>false</holder>
            <optics>false</optics>
        </ttc>
        <material>steel, plastic</material>
    </weapon>
</gun>
